export const GET_ERRORS = "GET_ERRORS";
export const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
export const GET_AUTH = "GET_AUTH";
export const GET_CHOOSE = "GET_CHOOSE";
export const SIGNED_OUT = "SIGNED_OUT";
export const DELETE_ONE_TASK = "DELETE_ONE_TASK";

export const DELETE_MENU_TASK = "DELETE_MENU_TASK";

export const SUCCESS_BUY_PRODUCT = "SUCCESS_BUY_PRODUCT";

export const GET_ORDERS_TASKS = "GET_ORDERS_TASKS";